#!/bin/bash
# Blender简单修改工作流程

echo "=== Blender STL修改工作流程 ==="
echo ""
echo "步骤1: 备份原文件"
echo "----------------------------------------"
echo "cd $(pwd)"
echo "cp src/dog2_description/meshes/base_link.STL src/dog2_description/meshes/base_link.STL.backup"
echo ""
echo "步骤2: 在Blender中打开STL"
echo "----------------------------------------"
echo "1. 打开Blender"
echo "2. 删除默认的立方体（选中后按X → Delete）"
echo "3. File → Import → STL (.stl)"
echo "4. 选择文件：$(pwd)/src/dog2_description/meshes/base_link.STL"
echo ""
echo "步骤3: 修改模型"
echo "----------------------------------------"
echo "基础操作："
echo "  Tab        - 进入/退出编辑模式"
echo "  G          - 移动（Grab）"
echo "  S          - 缩放（Scale）"
echo "  R          - 旋转（Rotate）"
echo "  E          - 挤出（Extrude）"
echo "  X          - 删除"
echo "  鼠标滚轮   - 缩放视图"
echo "  鼠标中键   - 旋转视图"
echo ""
echo "步骤4: 导出STL"
echo "----------------------------------------"
echo "1. File → Export → STL (.stl)"
echo "2. 导出设置："
echo "   ✓ Scene Unit"
echo "   ✓ Apply Modifiers"
echo "3. 保存到：$(pwd)/src/dog2_description/meshes/base_link.STL"
echo "   （覆盖原文件）"
echo ""
echo "步骤5: 测试"
echo "----------------------------------------"
echo "cd $(pwd)"
echo "colcon build --packages-select dog2_description"
echo "source install/setup.bash"
echo "ros2 launch dog2_description view_dog2.launch.py"
echo ""
echo "=== 可修改的部件列表 ==="
echo "机身: base_link.STL"
echo "左前腿: l1.STL, l11.STL, l111.STL"
echo "右前腿: l2.STL, l21.STL, l211.STL"
echo "左后腿: l3.STL, l31.STL, l311.STL"
echo "右后腿: l4.STL, l41.STL, l411.STL"
